### ISSUE TITLE
pulumi-databricks provider errors

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi-tf-provider-boilerplate#36]
That's my first pulumi provider, I've built it here: https://github.com/XBeg9/pulumi-databricks/blob/master/provider/resources.go (will change the docs, when I will validate that it works correctly).

When I try to use Notebook resource in my TS project:

```typescript
new databricks.Notebook("hello", {
  language: "SCALA",
  content: "# First notebook",
  path: "/notebooks",
  format: "SOURCE",
  mkdirs: true,
  overwrite: false
});
```

I am getting such error:

```log
Error: failed to register new resource hello [databricks:index/notebook:Notebook]: 2 UNKNOWN: No Major.Minor.Patch elements found
        at Object.registerResource (/Users/fed/Projects/Fed/pulumi-databricks/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/resource.js:115:27)
        at new Resource (/Users/fed/Projects/Fed/pulumi-databricks/sdk/nodejs/node_modules/@pulumi/pulumi/resource.js:204:24)
        at new CustomResource (/Users/fed/Projects/Fed/pulumi-databricks/sdk/nodejs/node_modules/@pulumi/pulumi/resource.js:295:9)
        at new Notebook (/Users/fed/Projects/Fed/pulumi-databricks/sdk/nodejs/notebook.ts:44:9)
        at Object.<anonymous> (/Users/fed/Projects/Fed/etl_pipeline/src/databricks/cluster.ts:9:1)
        at Module._compile (internal/modules/cjs/loader.js:1156:30)
        at Module.m._compile (/Users/fed/Projects/Fed/etl_pipeline/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/fed/Projects/Fed/etl_pipeline/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:1000:32)
```

Any ideas?

Thanks

**Comment by XBeg9** [comment]
```typescript
const provider = new databricks.Provider(
  "databricks",
  {
    host: workspace.workspaceUrl,
    token: "****************"
  },
  {
    dependsOn: workspace
  }
);

new databricks.Notebook(
  "hello-world",
  {
    language: "SCALA",
    content: Base64.encode("# First notebook"),
    path: "/notebooks",
    format: "SOURCE",
    mkdirs: true,
    overwrite: false
  },
  {
    provider,
    dependsOn: workspace
  }
);
```

this strange error was removed by providing a custom provider, but now I am getting:

```bash
databricks:index:Notebook (hello-world):
    error: parse ":///api/2.0/workspace/mkdirs": missing protocol scheme
```

**Comment by stack72** [comment]
This doesn't look to be an issue anymore - we have had other 3rd party contributed providers. Sorry we didn't get back to you at this time :/
